# NOTE: generated by niv-util; run niv-util init to regenerate
opts:
import
  (builtins.fetchurl "https://raw.githubusercontent.com/timbertson/niv-util/c1b60458c9eda33f821f07436fcf0d20f4faef37/default.nix")
  ({ sourcesFile = ./sources.json; } // opts)

