# NOTE: generated by niv-util; run niv-util init to regenerate
opts:
import
  (builtins.fetchurl "https://raw.githubusercontent.com/timbertson/niv-util/8ea10ebe4df599443a84826bf0740377a53a181e/default.nix")
  ({ sourcesFile = ./sources.json; } // opts)

