#!/bin/bash
set -eu
if [ "${GUP_XTRACE:-}" = 1 ]; then
	set -x
	pwd
fi
gup --always
base="$(basename "$2" .js)"
if [ -f mode.sh ]; then
	gup -u mode.sh
	. mode.sh
else
	gup --ifcreate mode.sh
fi

if [ "${DEVELOPMENT:-}" = 1 ]; then
	tsc "./src/$base".ts --out "$1"
else
	tsc "./src/$base".ts \
			--alwaysStrict \
			--noImplicitAny \
			--noImplicitReturns \
			--noImplicitThis \
			--noUnusedParameters \
			--noUnusedLocals \
			--outFile "$1"
fi
