#!/bin/bash
set -eu
gup --always
base="$(basename "$2" .js)"
tsc "./src/$base".ts \
		--alwaysStrict \
		--noImplicitAny \
		--noImplicitReturns \
		--noImplicitThis \
		--noUnusedParameters \
		--noUnusedLocals \
		--out "$1"

